import React,{useEffect,useState} from 'react';
import {doc,onSnapshot,collection,getDocs,query,orderBy,limit} from 'firebase/firestore';
import {getFunctions,httpsCallable} from 'firebase/functions';
import {db} from '../../firebase/config';
import {ModerationButton} from './ReportReviewControls';
export default function AccountModerationControls({targetUserId,ownAccount=false}) {
 const [state,setState]=useState(null),[reason,setReason]=useState(''),[days,setDays]=useState('7'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [history,setHistory]=useState([]);
 useEffect(()=>targetUserId?onSnapshot(doc(db,'users',targetUserId,'moderation','state'),snap=>setState(snap.data()||null),()=>setMessage('Account decisions could not be loaded.')):undefined,[targetUserId]);
 const restricted=state?.banned||state?.suspendedUntil?.toMillis()>Date.now();
 const run=async action=>{if(busy||!reason.trim())return;setBusy(true);try{await httpsCallable(getFunctions(),ownAccount?'appealAccountModeration':'moderateAccount')({targetUserId,action,reason,days});setReason('');setMessage(ownAccount?'Appeal received.':'Account decision saved.');}catch(error){setMessage(error.message);}finally{setBusy(false);}};
 if(ownAccount&&!state)return null;
 return <section className="p-4 border rounded-lg my-3"><h3 className="font-bold">Account moderation</h3><p>{restricted?(state.banned?'Account banned':'Account suspended until '+state.suspendedUntil.toDate().toLocaleString()):'No active account suspension'}</p>{state?.reason&&<p>{state.reason}</p>}{state?.appeal&&<p>Appeal: {state.appeal}</p>}
 {(!ownAccount||(restricted&&!state.appealPending))&&<><label className="block">{ownAccount?'Reason for account appeal':'Account decision reason'}<textarea maxLength={1000} className="w-full border rounded p-2" value={reason} onChange={event=>setReason(event.target.value)}/></label>{!ownAccount&&<label>Suspension duration<select value={days} onChange={event=>setDays(event.target.value)} className="border rounded m-2 p-2"><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option></select></label>}
 <div className="flex flex-wrap justify-end gap-2 bg-gray-50 p-3 mt-3">{ownAccount?<ModerationButton label="Appeal account decision" description="Request another review of this account sanction. Existing restrictions remain active." disabled={busy||!reason.trim()} onClick={()=>run('appeal')}/>:<>{[['warn','Warn','yellow'],['suspend','Suspend','red'],['ban','Ban','red'],['release','Lift restriction','green']].map(([action,label,color])=><ModerationButton key={action} label={label} color={color} description={{warn:'Record and deliver a warning without suspending the account.',suspend:'Block account writes and authenticated service actions for the selected duration.',ban:'Block account writes and authenticated service actions until a moderator lifts the restriction.',release:'Lift the account restriction and record your decision. Content holds remain unchanged.'}[action]} disabled={busy||!reason.trim()} onClick={()=>run(action)}/>)}</>}</div></>}
 {ownAccount&&state?.appealPending&&<p>Your account appeal is awaiting review.</p>}<details onToggle={async event=>{if(!event.currentTarget.open)return;try{const snapshot=await getDocs(query(collection(db,'users',targetUserId,'moderationHistory'),orderBy('createdAt','desc'),limit(30)));setHistory(snapshot.docs.map(doc=>({id:doc.id,...doc.data()})));}catch(error){setMessage(error.message);}}}><summary>Account decision history</summary>{history.map(item=><p key={item.id}>{item.createdAt?.toDate().toLocaleString()} — {item.action}: {item.reason}{!ownAccount&&` — ${item.actorDeleted?'Deleted user':item.actorUid}`}</p>)}</details>{message&&<p role="status">{message}</p>}</section>;
}
